spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth_dev
    username: root
    password: 12345678
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none